#!/usr/bin/env python3
"""Extract DiffBragg baseline from refine_one HDF5 output."""
import datetime
import json
from pathlib import Path
import h5py
import numpy as np

def main():
    report_dir = Path(__file__).resolve().parent
    legacy_dir = report_dir / "golden_dataset" / "legacy"
    legacy_dir.mkdir(parents=True, exist_ok=True)

    # Read the HDF5 file generated by refine_one
    h5_path = legacy_dir / "dbex_diffbragg_gpu.h5"
    if not h5_path.exists():
        raise RuntimeError(f"Expected HDF5 file not found: {h5_path}")

    with h5py.File(h5_path, "r") as f:
        # Extract the forward model (Bragg tensor)
        bragg = np.array(f["/bragg"][:], dtype=np.float32)

        # Extract metadata
        attrs = dict(f.attrs)

    # Save as NPY for consistency with the plan
    np.save(legacy_dir / "bragg_diffbragg.npy", bragg)

    # Create config JSON
    diff_meta = {
        "devId": 0,
        "shape": list(bragg.shape),
        "dtype": "float32",
        "max": float(bragg.max()),
        "min": float(bragg.min()),
        "source": "dbex.refine_one HDF5 /bragg",
        "h5_path": str(h5_path),
        "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
    }

    with open(legacy_dir / "config_diffbragg.json", "w") as fh:
        json.dump(diff_meta, fh, indent=2)

    print(f"[extract_diffbragg] Extracted DiffBragg baseline: {legacy_dir/'bragg_diffbragg.npy'}")
    print(f"[extract_diffbragg] Shape: {bragg.shape}, max: {bragg.max():.2f}")

if __name__ == "__main__":
    main()
